-- 2022년 1월의 도서 판매 데이터를 기준으로 저자별, 카테고리별 매출액 조회
-- 저자 ID 오름차순, 카테고리 내림차순
-- TOTAL_SALES=판매량 * 판매가

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID=A.AUTHOR_ID
JOIN BOOK_SALES AS S ON B.BOOK_ID=S.BOOK_ID
WHERE S.SALES_DATE LIKE ('2022-01%')
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;
