-- 자동차 종류가 '세단' 또는 'SUV'인 자동차 중
-- 2022년 11월 1일부터 11월 30일까지 대여 가능하고
-- 30일간 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 대여 금액 기준 내림차순, 종류 오름차순, id 내림차순
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE,
       FLOOR(DAILY_FEE*(100-DISCOUNT_RATE)/100*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
WHERE P.DURATION_TYPE='30일 이상'
      AND C.CAR_TYPE IN ('세단', 'SUV')
      AND C.CAR_ID NOT IN (SELECT CAR_ID
                          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                          WHERE END_DATE>'2022-11-01' AND START_DATE<'2022-12-01')
      AND FLOOR(DAILY_FEE*(100-DISCOUNT_RATE)/100*30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;