-- 대장균 개체의 크기를 내림차순 정렬
-- 상위 0-25 CRITICAL, 26-50 HIGH
-- 51-75 MEDIUM, 76-100 LOW

SELECT ID, 
    (CASE 
     WHEN PCT<=0.25 THEN 'CRITICAL'
     WHEN PCT<=0.5 THEN 'HIGH'
     WHEN PCT<=0.75 THEN 'MEDIUM'
     ELSE 'LOW' 
     END) AS COLONY_NAME
FROM (
    SELECT *, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PCT
    FROM ECOLI_DATA
) AS E
ORDER BY ID ASC;
