-- 서울에 위치한 식당 정보 조회
-- 리뷰 평균점수는 소수점 세번째 자리에서 반올림
-- 결과는 평균점수를 기준으로 내림차순 정렬, 즐겨찾기 수 내림차순 정렬
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES,
       A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A
INNER JOIN REST_REVIEW AS B
ON A.REST_ID=B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;