-- 년, 월, 성별 별로 상품을 구매한 회원수 집계 -> 오름차순 정렬
-- 성별 정보가 없는 경우, 결과에서 제외

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
       GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO AS I
JOIN ONLINE_SALE AS S ON I.USER_ID=S.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;