-- 물고기의 종류별 물고기의 이름과 잡은 수를 출력
-- 잡은 수를 기준으로 내림차순 정렬

SELECT COUNT(B.FISH_NAME) AS FISH_COUNT, B.FISH_NAME
FROM FISH_INFO AS A
LEFT JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE=B.FISH_TYPE
GROUP BY B.FISH_NAME
ORDER BY COUNT(B.FISH_NAME) DESC;