-- 아직 입양을 못 간 동물 중 가장 보호소에 오래 있었던 동물 3마리
-- 보호 시작일 오름차순

SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME LIMIT 3;