-- 생산일자가 2022년 5월인 식품 조회
-- 총매출 내림차순, 식품ID 오름차순

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS O
JOIN FOOD_PRODUCT AS P ON O.PRODUCT_ID=P.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE ('2022-05%')
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;