-- 완료된 중고 거래의 총금액이 70만원 이상인 회원 조회
-- 총거래금액을 기준으로 오름차순 정렬

SELECT USER_ID, NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U
ON B.WRITER_ID=U.USER_ID
WHERE B.STATUS='DONE'
GROUP BY U.USER_ID
HAVING SUM(B.PRICE)>=700000
ORDER BY SUM(B.PRICE);