-- 리뷰를 가장 많이 작성한 회원의 리뷰 조회
-- 리뷰 작성일 오름차순, 리뷰 텍스트 오름차순
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS P
JOIN REST_REVIEW AS R ON P.MEMBER_ID=R.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_SCORE) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;