-- 2022년도 한해 평가 점수가 가장 높은 사원 정보 조회
SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_EMPLOYEES AS B
JOIN HR_GRADE AS C
ON B.EMP_NO=C.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING C.YEAR='2022'
ORDER BY SCORE DESC
LIMIT 1;