-- 2022년 1월 카테고리별 도서 판매량 합산
-- 카테고리명을 기준으로 오름차순

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS A
JOIN BOOK_SALES AS B
ON A.BOOK_ID=B.BOOK_ID
WHERE YEAR(SALES_DATE)='2022' AND MONTH(SALES_DATE)='01'
GROUP BY CATEGORY
ORDER BY CATEGORY;
